on:
  push:
    branches: [master-pipeline]
  pull_request:
    branches: [ master-pipeline ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 5.0.x
      - name: Restore de-endencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
